name: Submit PPA

on:
  workflow_dispatch:
    inputs:
      user:
        required: true
        type: string
      ppa_name:
        required: true
        type: string
      description:
        required: true
        type: string
      version:
        required: true
        type: string
      license:
        required: true
        type: string

jobs:
  submit-ppa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add PPA YAML
      run: |
        mkdir -p docs/${{ github.event.inputs.user }}
        cat <<EOF > docs/${{ github.event.inputs.user }}/${{ github.event.inputs.ppa_name }}.yml
name: ${{ github.event.inputs.ppa_name }}
description: ${{ github.event.inputs.description }}
version: ${{ github.event.inputs.version }}
license: ${{ github.event.inputs.license }}
EOF

    - name: Commit & Push
      run: |
        git config user.name "HighBit Bot"
        git config user.email "actions@github.com"
        git add docs/
        git commit -m "Submit PPA: ${{ github.event.inputs.ppa_name }}"
        git push
